import React, { useState } from 'react';
import { PayrollRun, Payslip, SystemConfig } from '../types';
import { formatCurrency } from '../utils/currency';
import { FileText, Printer, Search, Eye, X } from 'lucide-react';

interface PayslipsTabProps {
  payrollRuns: PayrollRun[];
  config: SystemConfig;
}

export const PayslipsTab: React.FC<PayslipsTabProps> = ({ payrollRuns, config }) => {
  const [selectedPayslip, setSelectedPayslip] = useState<Payslip | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  // Flatten all payslips across runs
  const allPayslips: Payslip[] = [];
  payrollRuns.forEach(run => {
    run.payslips.forEach(p => allPayslips.push(p));
  });

  const filteredPayslips = allPayslips.filter(p => 
    `${p.employeeName} ${p.employeeCode} ${p.department} ${p.period}`
      .toLowerCase()
      .includes(searchQuery.toLowerCase())
  );

  const handlePrint = (payslipId: string) => {
    window.open(`/api/payroll/payslips/${payslipId}/print`, '_blank');
  };

  return (
    <div id="payslips-tab-content" className="space-y-6">
      {/* Header Bar */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-5 rounded-lg border border-slate-200 shadow-xs">
        <div>
          <h2 className="text-base font-bold text-slate-800">Digital Payslips Portal</h2>
          <p className="text-xs text-slate-500 mt-0.5">Generated by <code className="text-blue-600 font-mono">PayslipService</code>. Printable and ready for distribution.</p>
        </div>

        <div className="relative w-full md:w-72">
          <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400" />
          <input
            id="input-search-payslips"
            type="text"
            placeholder="Search employee, ID, period..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            className="w-full bg-white border border-slate-300 rounded pl-9 pr-3 py-2 text-xs text-slate-800 placeholder-slate-400 focus:outline-none focus:border-blue-500 shadow-xs"
          />
        </div>
      </div>

      {/* Payslips Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredPayslips.map(ps => (
          <div
            key={ps.id}
            className="p-4 bg-white border border-slate-200 hover:border-slate-300 rounded-lg space-y-3 transition-all shadow-xs"
          >
            <div className="flex justify-between items-start border-b border-slate-200 pb-2.5">
              <div>
                <span className="text-[10px] bg-blue-100 text-blue-700 px-2 py-0.5 rounded font-mono font-bold">
                  {ps.period}
                </span>
                <h3 className="text-sm font-bold text-slate-900 mt-1.5">{ps.employeeName}</h3>
                <p className="text-[11px] text-slate-500">{ps.department} • {ps.position}</p>
              </div>

              <div className="text-right">
                <span className="text-[10px] text-slate-500 block uppercase font-semibold">NET SALARY</span>
                <span className="text-base font-bold text-blue-600 font-mono">
                  {formatCurrency(ps.netPay, config.currencySymbol)}
                </span>
              </div>
            </div>

            {/* Quick Breakdown */}
            <div className="grid grid-cols-2 gap-2 text-[11px] bg-slate-50 p-2.5 rounded border border-slate-200 font-mono">
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-sans font-semibold">Gross Pay</span>
                <span className="text-slate-800 font-semibold">{formatCurrency(ps.grossPay, config.currencySymbol)}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-sans font-semibold">Deductions</span>
                <span className="text-red-600 font-semibold">-{formatCurrency(ps.totalDeductions, config.currencySymbol)}</span>
              </div>
            </div>

            <div className="flex gap-2 pt-1">
              <button
                id={`btn-view-slip-${ps.id}`}
                onClick={() => setSelectedPayslip(ps)}
                className="flex-1 flex items-center justify-center gap-1.5 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 text-xs font-semibold py-1.5 rounded transition-all cursor-pointer shadow-xs"
              >
                <Eye className="w-3.5 h-3.5 text-blue-600" />
                <span>Inspect</span>
              </button>

              <button
                id={`btn-print-slip-${ps.id}`}
                onClick={() => handlePrint(ps.id)}
                className="flex items-center justify-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold px-3 py-1.5 rounded transition-all cursor-pointer shadow-xs"
                title="Open Printable HTML Slip"
              >
                <Printer className="w-3.5 h-3.5" />
                <span>Print</span>
              </button>
            </div>
          </div>
        ))}

        {filteredPayslips.length === 0 && (
          <div className="col-span-full py-12 text-center text-slate-500 text-xs bg-white border border-slate-200 rounded-lg shadow-xs">
            No generated payslips match your search criteria. Execute a payroll run to generate payslips.
          </div>
        )}
      </div>

      {/* Payslip Inspection Modal */}
      {selectedPayslip && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white border border-slate-200 rounded-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto p-6 space-y-5 text-slate-800 shadow-xl">
            <div className="flex justify-between items-center border-b border-slate-200 pb-3">
              <div>
                <span className="text-xs text-blue-600 font-mono font-bold">PERIOD: {selectedPayslip.period}</span>
                <h3 className="text-base font-bold text-slate-900 mt-0.5">{selectedPayslip.employeeName} - Payslip Breakdown</h3>
              </div>
              <button
                onClick={() => setSelectedPayslip(null)}
                className="text-slate-400 hover:text-slate-600 cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Employee Meta Details */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 bg-slate-50 p-4 rounded border border-slate-200 text-xs">
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-semibold">Employee Code</span>
                <span className="font-bold font-mono text-slate-900">{selectedPayslip.employeeCode}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-semibold">Department</span>
                <span className="font-medium text-slate-800">{selectedPayslip.department}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-semibold">Position</span>
                <span className="font-medium text-slate-800">{selectedPayslip.position}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-semibold">Payment IBAN</span>
                <span className="font-mono text-slate-700">{selectedPayslip.bankIban}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-semibold">Working / Absent</span>
                <span className="text-slate-800 font-mono">{selectedPayslip.workingDays}d / {selectedPayslip.absentDays}d</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px] uppercase font-semibold">Overtime Hours</span>
                <span className="text-slate-800 font-mono">{selectedPayslip.overtimeHours} hrs</span>
              </div>
            </div>

            {/* Itemized Table */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider">Itemized Breakdown</h4>
              <div className="bg-white rounded border border-slate-200 overflow-hidden">
                <table className="w-full text-left text-xs border-collapse">
                  <thead className="bg-slate-50 text-slate-500 font-semibold border-b border-slate-200">
                    <tr>
                      <th className="py-2 px-3">Item Description</th>
                      <th className="py-2 px-3">Category</th>
                      <th className="py-2 px-3 text-right">Amount</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 font-mono text-slate-800">
                    {selectedPayslip.items.map((item, idx) => (
                      <tr key={idx} className="hover:bg-slate-50">
                        <td className="py-2 px-3 font-sans text-slate-900 font-medium">{item.label}</td>
                        <td className="py-2 px-3 font-sans">
                          <span className={`text-[10px] px-2 py-0.5 rounded font-bold uppercase ${
                            item.category === 'earnings'
                              ? 'bg-green-100 text-green-700'
                              : item.category === 'deductions'
                              ? 'bg-red-100 text-red-700'
                              : 'bg-blue-100 text-blue-700'
                          }`}>
                            {item.category}
                          </span>
                        </td>
                        <td className={`py-2 px-3 text-right font-bold ${
                          item.category === 'earnings' ? 'text-green-700' : 'text-red-600'
                        }`}>
                          {item.category === 'deductions' ? '-' : ''}{formatCurrency(item.amount, config.currencySymbol)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Total Footer */}
            <div className="p-4 rounded bg-slate-50 border border-slate-200 flex justify-between items-center text-xs">
              <div>
                <span className="text-slate-600 block">Gross: {formatCurrency(selectedPayslip.grossPay, config.currencySymbol)}</span>
                <span className="text-slate-600 block">Deductions: {formatCurrency(selectedPayslip.totalDeductions, config.currencySymbol)}</span>
              </div>
              <div className="text-right">
                <span className="text-slate-500 uppercase text-[10px] font-semibold block">Net Payable Salary</span>
                <span className="text-xl font-bold text-blue-600 font-mono">
                  {formatCurrency(selectedPayslip.netPay, config.currencySymbol)}
                </span>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                onClick={() => setSelectedPayslip(null)}
                className="px-3.5 py-1.5 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 text-xs font-semibold rounded cursor-pointer"
              >
                Close
              </button>
              <button
                onClick={() => handlePrint(selectedPayslip.id)}
                className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded flex items-center gap-1.5 cursor-pointer shadow-xs"
              >
                <Printer className="w-4 h-4" />
                <span>Open Printable HTML</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
