import React from 'react';
import { PayrollRun, AuditLog } from '../types';
import { Download, FileSpreadsheet, ShieldAlert, FileText } from 'lucide-react';

interface ReportsTabProps {
  payrollRuns: PayrollRun[];
  auditLogs: AuditLog[];
}

export const ReportsTab: React.FC<ReportsTabProps> = ({ payrollRuns, auditLogs }) => {
  const handleDownloadWps = (runId: string) => {
    window.open(`/api/reports/wps/${runId}`, '_blank');
  };

  const handleDownloadCsv = (runId: string) => {
    window.open(`/api/reports/csv/${runId}`, '_blank');
  };

  return (
    <div id="reports-export-tab" className="space-y-6">
      {/* Banner */}
      <div className="p-5 bg-white border border-slate-200 rounded-lg shadow-xs">
        <h2 className="text-base font-bold text-slate-800">Wage Protection System (WPS) & Financial Reports</h2>
        <p className="text-xs text-slate-500 mt-0.5">
          Export bank-compliant WPS text files and itemized CSV payroll rolls generated by <code className="text-blue-600 font-mono">PayrollExportService</code>.
        </p>
      </div>

      {/* Available Payroll Runs to Export */}
      <div className="bg-white border border-slate-200 rounded-lg p-5 space-y-4 shadow-xs">
        <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Generated Exports By Pay Period</h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {payrollRuns.map(run => (
            <div key={run.id} className="p-4 bg-slate-50 border border-slate-200 rounded space-y-3">
              <div className="flex justify-between items-center">
                <div>
                  <span className="text-[10px] text-blue-700 font-mono font-bold">PERIOD: {run.period}</span>
                  <h4 className="text-sm font-bold text-slate-900 mt-0.5">{run.title}</h4>
                </div>
                <span className="text-xs font-bold text-blue-600 font-mono">
                  SAR {run.totalNetPay}
                </span>
              </div>

              <div className="flex gap-2 pt-1">
                <button
                  id={`btn-download-wps-${run.id}`}
                  onClick={() => handleDownloadWps(run.id)}
                  className="flex-1 flex items-center justify-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold py-1.5 rounded transition-all cursor-pointer shadow-xs"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>Download WPS (.txt)</span>
                </button>

                <button
                  id={`btn-download-csv-${run.id}`}
                  onClick={() => handleDownloadCsv(run.id)}
                  className="flex-1 flex items-center justify-center gap-1.5 bg-green-600 hover:bg-green-700 text-white text-xs font-semibold py-1.5 rounded transition-all cursor-pointer shadow-xs"
                >
                  <FileSpreadsheet className="w-3.5 h-3.5" />
                  <span>Download CSV</span>
                </button>
              </div>
            </div>
          ))}

          {payrollRuns.length === 0 && (
            <div className="col-span-full py-8 text-center text-slate-500 text-xs">
              No calculated payroll runs available for export yet.
            </div>
          )}
        </div>
      </div>

      {/* Audit Logs Section */}
      <div className="bg-white border border-slate-200 rounded-lg p-5 space-y-4 shadow-xs">
        <div className="flex items-center gap-2">
          <ShieldAlert className="w-4 h-4 text-blue-600" />
          <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Security & Execution Audit Trail</h3>
        </div>

        <div className="space-y-2 text-xs font-mono">
          {auditLogs.map(log => (
            <div key={log.id} className="p-3 bg-slate-50 border border-slate-200 rounded flex items-start justify-between gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold text-blue-700">{log.action}</span>
                  <span className="text-[10px] bg-slate-200 text-slate-700 px-2 py-0.5 rounded font-semibold">{log.module}</span>
                </div>
                <p className="text-slate-800 font-sans mt-1 text-xs">{log.details}</p>
              </div>

              <div className="text-right text-slate-500 text-[10px] shrink-0">
                <div>{new Date(log.timestamp).toLocaleDateString()}</div>
                <div>{new Date(log.timestamp).toLocaleTimeString()}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
